@startuml
title Run Application

skinparam shadowing false
skinparam state {
  BackgroundColor #F8F9FB
  BorderColor #3A3A3A
  ArrowColor #3A3A3A
}

[*] --> S0 : start

state "S0: Авторизация" as S0
state "S1: Карта (покой)" as S1
state "S2: Обратный отсчёт" as S2
state "S3: Активный забег" as S3
state "S4: Пауза забега" as S4
state "S5: Завершение забега" as S5
state "S6: Итоги забега" as S6
state "S7: История забегов" as S7
state "S8: Профиль" as S8

S0 --> S1 : T0 / Успешный вход/регистрация
S0 --> S0 : T1 / Неверные данные

S1 --> S2 : T2 / Нажатие «Старт»
S2 --> S3 : T3 / Завершение отсчёта
S3 --> S4 : T4 / Нажатие «Пауза»
S4 --> S3 : T5 / Нажатие «Продолжить»

S3 --> S5 : T6 / Нажатие «Стоп/Финиш»
S4 --> S5 : T6 / Нажатие «Стоп/Финиш»
S5 --> S6 : T7 / Сервер обработал забег
S5 --> S1 : T8 / Ошибка завершения
S6 --> S1 : T9 / Нажатие «Готово» или «Назад»

S1 --> S7 : T10 / Переход на вкладку «История»
S1 --> S8 : T11 / Переход на вкладку «Профиль»
S7 --> S1 : T12 / Переход на вкладку «Карта»
S8 --> S1 : T12 / Переход на вкладку «Карта»
S8 --> S0 : T13 / Нажатие «Выход»

@enduml
